FROM jenkins/jenkins:lts

USER root
RUN apt-get update

# Install Python
RUN apt-get install -y \
        build-essential \
        zlib1g-dev \
        libncurses5-dev \
        libgdbm-dev \
        libnss3-dev \
        libssl-dev \
        libreadline-dev \
        libffi-dev \
        libsqlite3-dev \
        wget \
        libbz2-dev
RUN wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz && \
        tar -xvf Python-3.10.0.tgz && \
        cd Python-3.10.0 && \
        ./configure --enable-optimizations && \
        make -j 2 && \
        make altinstall && \
        python3.10 --version

# Install Google Chrome
# Check versions at: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
RUN CHROME_VERSION="113.0.5672.92-1" && \
    wget -O google-chrome.deb "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb" && \
    apt-get install -y -f ./google-chrome.deb && \
    rm google-chrome.deb && \
    google-chrome --version

USER jenkins
